---
title: "11.1 Besoins des ménages et enjeux particuliers"
author: "Curbcut"
output: html_document
---

```{r setup_11_1, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
```

# 11.1.1 Écart entre les besoins actuels de logement des ménages et l’offre résidentielle actuelle

## Rental supply and demand

### ANGLAIS

From 2016 to 2021, the City saw a substantial shift to rental housing. Tenant-occupied households were 30.5% of all private households in 2016, but 33.5% in 2021: a 9.8% increase in just five years, and a larger shift in this proportion than at any other point since 2001. This trend is highly likely to continue, given the fact that very little new ownership housing is being produced, while rental construction has been robust. From 2019-2023, 77% (1,598 units) of the 2,074 average annual housing starts were intended for the rental market. In fact, far more rental housing is being initiated in Laval now than at any point since 1990.

Despite the strong pace of rental construction, however, aggregated market signals suggest that demand for rental housing is running substantially above supply. First, new renter household formation has run substantially ahead of new rental construction. From 2016 to 2021, the number of tenant-occupied private households increased by 7,760, while only 3,290 rental unit housing starts were recorded in the corresponding (2014-2018) five-year period. This implies that some rental housing demand was fulfilled through conversions of ownership housing to rental housing, and that some demand was fulfilled through new secondary rental market housing (specifically, condominiums).

Second, after a period of relative stagnation in the 1990s, there has been a large increase in rents and a large decline in the vacancy rate in the last 20 years, with particularly rapid changes in both these indicators since 2010. When vacancy rates are below 3%, rents should be expected to increase due to high levels of tenant competition for units; the vacancy rate has averaged 1.9% over the last four years. The implication is that the City will require robust rental housing construction in the years to prevent further large rent increases.

However, there is also an indication that supply and demand have become disconnected in different submarkets of the rental sector. The vacancy rate has fallen dramatically for the largest units; for 3+ bedroom units the average 2019-2023 vacancy rate was only 1.0%. It has also fallen quickly among lower-priced units. However, there has been a substantial *increase* in vacancy rate among expensive, newly built units. These units are not being absorbed as they come on the market. To some extent this is a natural pattern (new units often have higher vacancy rates than older units), but the pattern is stronger than at any point in the last 35 years.

This suggests the possibility of a mismatch between new rental supply (higher-end units) and current demand (lower-end units with 3 or more bedrooms).

### FRANÇAIS

De 2016 à 2021, la Ville a connu un important glissement vers le logement locatif. Les ménages locataires représentaient 30,5 % de l'ensemble des ménages privés en 2016, mais 33,5 % en 2021 : une augmentation de 9,8 % en seulement cinq ans, soit un changement plus important de cette proportion que jamais depuis 2001. Cette tendance est très susceptible de se poursuivre, étant donné que très peu de nouveaux logements en propriété sont construits, tandis que la construction locative est demeurée vigoureuse. De 2019 à 2023, 77 % (1 598 unités) des 2 074 mises en chantier annuelles moyennes de logements visaient le marché locatif. En fait, bien plus de logements locatifs sont actuellement lancés à Laval qu'à tout autre moment depuis 1990.

Cependant, malgré le rythme soutenu de construction locative, les indicateurs de marché agrégés montrent que la demande de logements locatifs dépasse largement l'offre. Premièrement, la formation de nouveaux ménages locataires a été largement supérieure à la nouvelle construction locative. De 2016 à 2021, le nombre de ménages privés locataires a augmenté de 7 760, alors que seulement 3 290 mises en chantier de logements locatifs ont été enregistrées sur la période de cinq ans correspondante (2014-2018). Cela implique que la demande de logements locatifs a été partiellement satisfaite par des conversions de logements en propriété vers des logements locatifs, et que d’autres besoins ont été comblés par de nouveaux logements locatifs sur le marché secondaire (notamment des condominiums).

Deuxièmement, après une période de relative stagnation dans les années 1990, les loyers ont fortement augmenté et le taux d’inoccupation a fortement diminué au cours des 20 dernières années, avec des changements particulièrement rapides dans ces deux indicateurs depuis 2010. Lorsque les taux d'inoccupation sont inférieurs à 3 %, les loyers devraient augmenter en raison d'une forte concurrence des locataires pour les logements; le taux d’inoccupation a atteint en moyenne 1,9 % au cours des quatre dernières années. Cela signifie que la Ville devra maintenir une construction vigoureuse de logements locatifs dans les années à venir pour éviter de nouvelles augmentations importantes des loyers.

Il semble cependant qu'une déconnexion entre l'offre et la demande soit apparue dans différents sous-marchés du secteur locatif. Le taux d'inoccupation a chuté de manière marquée pour les logements de grande taille; pour les unités de 3 chambres ou plus, le taux d'inoccupation moyen de 2019-2023 n'était que de 1,0 %. Il a également rapidement diminué parmi les unités à prix plus bas. Cependant, on observe une augmentation substantielle du taux d'inoccupation parmi les unités neuves et coûteuses. Ces unités ne sont pas absorbées dès leur mise en marché. Dans une certaine mesure, il s'agit d'un phénomène naturel (les unités neuves présentent souvent des taux d'inoccupation plus élevés que les unités plus anciennes), mais ce phénomène est plus marqué que jamais depuis les 35 dernières années.

Cela suggère la possibilité d'un déséquilibre entre la nouvelle offre locative (unités haut de gamme) et la demande actuelle (unités de bas de gamme avec 3 chambres ou plus).

## Rental versus ownership

### ANGLAIS

Although there has been a noticeable shift away from homeownership and towards rental housing in the last five years, it remains the case that two thirds of Laval households are homeowners. However, there has been significant decline in new homeownership construction; there were only an average of 224 homeownership starts and 251 condominimum starts per year from 2019-2023, compared to 1,598 rental starts per year in the same time period, and compared to 735 homeownership starts and 1,035 condominium starts per year in the 2009-2013 time period.

In addition to the general need for more housing starts and the specific need for more rental housing starts, therefore, additional homeownership units are going to be required, and given the relative scarcity of new greenfield opportunities the most plausible way to continue building for the ownership market will be through condominiums. However, a comparison of ownership household formation with new construction suggests that a large proportion of recent condominium construction has in fact entered the second rental market. From 2016 to 2021, the total number of owner-occupied private dwelling units increased by 1,720. During the five-year 2014-2018 period, there were 1,505 homeowner housing starts and 4,025 condominium starts. Even allowing for some attrition of existing homeowner units during this time period, it remains the most likely conclusion that many or most of the condominium construction ended in the secondary rental market. This means that producing sufficient ownership housing to meet future demand in Laval will also require meeting rental housing demand, so that a higher proportion of condominium units remain in the ownership sector.

### FRANÇAIS

Bien qu’il y ait eu un déplacement notable de la propriété vers le logement locatif au cours des cinq dernières années, il reste que les deux tiers des ménages lavallois sont propriétaires de leur logement. Cependant, on observe un déclin significatif dans la construction de nouvelles unités en propriété : en moyenne, seules 224 unités de propriété et 251 unités en copropriété ont été mises en chantier par année entre 2019 et 2023, comparativement à 1 598 mises en chantier de logements locatifs par an sur la même période, et à 735 mises en chantier de propriétés et 1 035 de copropriétés par an entre 2009 et 2013.

En plus du besoin général d’augmenter les mises en chantier de logements et du besoin spécifique d’augmenter les logements locatifs, des unités en propriété supplémentaires seront également nécessaires. Compte tenu de la rareté relative des nouvelles opportunités en zones vierges, la manière la plus plausible de continuer à construire pour le marché de la propriété passe par les copropriétés. Cependant, une comparaison entre la formation de ménages propriétaires et la nouvelle construction suggère qu'une grande proportion des nouvelles constructions en copropriété a en réalité intégré le marché locatif secondaire. De 2016 à 2021, le nombre total de logements privés occupés par des propriétaires a augmenté de 1 720. Durant la période de cinq ans 2014-2018, il y a eu 1 505 mises en chantier pour des unités en propriété et 4 025 pour des copropriétés. Même en tenant compte de la perte de certaines unités existantes en propriété durant cette période, il est fort probable que beaucoup, voire la majorité des nouvelles copropriétés, se soient retrouvées sur le marché locatif secondaire. Cela signifie que pour produire suffisamment de logements en propriété pour répondre à la demande future à Laval, il sera également nécessaire de répondre à la demande en logements locatifs, afin qu'une proportion plus élevée de copropriétés reste dans le secteur de la propriété.


# 11.1.2 Écart entre les besoins actuels de logement et services des ménages et l’offre

### ANGLAIS

From 2011 to 2021 there has been a clear shift in large dwelling units, with both the absolute and proportional number of 3-bedroom units declining and the absolute and proportional number of 4+ bedroom units increasing. Although we do not have data on housing starts by bedroom count, it is very likely that this trend reflects a shift to nearly all single-family home construction featuring 4+ bedroom units, alongside attrition among previously build 3-bedroom units. At the same time, from the perspective of family-size versus non-family-size units, bedroom counts have been basically stable: three-bedrooms have been replaced with four+ bedrooms, but the total percentage of family-sized (3+) units has remained the same since 2011. Meanwhile, the rental vacancy rate among 3+ bedroom units has declined much faster than for other bedroom types, implying that the market is not producing enough of these units to satisfy demand.

An implication is that the supply of family-sized units has most been achieved through single-family homes, and as the amount of new single-family home construction has declined, there is an increasingly large gap between the supply of these larger units and the demand for them, particularly in the rental sector.

### FRANÇAIS

Entre 2011 et 2021, on observe un changement notable dans la distribution des grands logements : le nombre absolu et proportionnel d'unités de trois chambres a diminué, tandis que celui des unités de quatre chambres ou plus a augmenté. Bien que nous ne disposions pas de données sur les mises en chantier par nombre de chambres, il est très probable que cette tendance reflète une orientation vers la construction de maisons unifamiliales comportant principalement quatre chambres ou plus, ainsi qu'une attrition des unités de trois chambres existantes. En termes de taille des unités adaptées aux familles, le nombre de chambres est resté relativement stable : les unités de trois chambres ont été remplacées par des unités de quatre chambres et plus, mais la proportion totale de logements de taille familiale (trois chambres ou plus) est restée constante depuis 2011.

Cependant, le taux d’inoccupation locatif des unités de trois chambres et plus a diminué beaucoup plus rapidement que pour les autres types de logements, ce qui indique une offre insuffisante pour répondre à la demande. En conséquence, la majorité des unités de taille familiale semblent provenir des maisons unifamiliales. Étant donné le déclin des mises en chantier de maisons unifamiliales, un écart de plus en plus important se creuse entre l'offre de ces grandes unités et la demande, surtout dans le secteur locatif.


# 11.1.3 Variation du nombre et des parts de logements par type de construction résidentielle

### ANGLAIS

Two major trends have been observed in housing construction in Laval: First, a progressive shift from single-family home construction (in the 1990s and 2000s) to condominium construction (in the late 2000s and early 2010s) to purpose-built rental (since the 2010s). Second, a general slowing of new housing starts since the 2000s, from an annual average of 3,048 new starts at the 2000s intra-cycle peak (2004-2008) to 2,074 new starts at the most recent intra-cycle peak (2019-2023). The combination of these trends suggests both a continuation of the recently observed trend towards proportionately more renter households, and a future declining rate of new household formation in the absence of policy supports to encourage new residential investment.

### FRANÇAIS

Deux grandes tendances ont été observées dans la construction de logements à Laval : premièrement, un déplacement progressif de la construction de maisons unifamiliales (dans les années 1990 et 2000) vers la construction de copropriétés (à la fin des années 2000 et au début des années 2010), puis vers le locatif destiné spécifiquement au marché locatif (depuis les années 2010). Deuxièmement, un ralentissement général des nouvelles mises en chantier depuis les années 2000, passant d'une moyenne annuelle de 3 048 nouvelles mises en chantier au pic intra-cycle des années 2000 (2004-2008) à 2 074 nouvelles mises en chantier au pic intra-cycle le plus récent (2019-2023). La combinaison de ces tendances suggère à la fois la poursuite de l'augmentation proportionnelle des ménages locataires observée récemment, et un ralentissement futur de la formation de nouveaux ménages en l'absence de mesures politiques pour encourager de nouveaux investissements résidentiels.

# 11.1.4 Besoins en fonction des projections démographiques et autres

### ANGLAIS

The ISQ is projecting a slowing rate of household growth in Laval over the next 20 years (14.4% growth to 194,188 households by 2041, or 0.68% growth per year, compared to 0.95% growth per year from 2011-2021). Housing development patterns of the last ten years suggests that this amount of growth will be easily accommodated given existing trends.

From 2009 to 2018, there were 20,455 total housing starts in Laval. In relation to the stock of private dwelling units in 2011, this represents effectively a 1.27% annual growth rate in gross housing stock (i.e. not net of demolitions and other housing stock attrition). This housing stock growth rate was able to sustain a 0.95% annual growth in households. To achieve the ISQ's projected 0.68% growth rate for the next 20 years at the same ratio of housing construction to household formation would imply a gross annual housing stock growth rate of 0.91%. Working off the base of 166,610 privately occupied dwelling units in 2021, this implies roughly 1,650 new housing starts per year over the next 20 years. In fact, this figure is substantially smaller than the amount of units initiated at any point since the late 1990s.

The conclusion is that existing trends in housing development should be sufficient to support the ISQ's total expected growth in Laval households over the next two decades. There are, however, several other demographic patterns to note. We have already observed the shift in tenure from ownership to rental which has been underway since 2016. This shift is likely to continue, absent major changes to the future development pipeline. Second, we have observed an increase in single-person households in Laval over the last 25 years. This trend arguably reflects Laval's changing position in the greater Montreal region, as it has moved from bedroom community to central city, and this trend should be expected to continue in the absence of new future investments in family-sized housing units. Finally, TKTK older adults TKTK to be added.

### FRANÇAIS

L'ISQ projette un ralentissement de la croissance des ménages à Laval au cours des 20 prochaines années (une croissance de 14,4 % pour atteindre 194 188 ménages d'ici 2041, soit une croissance annuelle de 0,68 %, comparativement à 0,95 % par an entre 2011 et 2021). Les tendances récentes en matière de développement résidentiel suggèrent que ce niveau de croissance sera facilement absorbé.

De 2009 à 2018, Laval a enregistré un total de 20 455 mises en chantier. Par rapport au parc de logements privés en 2011, cela représente un taux de croissance annuelle de 1,27 % du parc résidentiel brut (c.-à-d. sans déduire les démolitions et autres réductions de parc). Ce taux de croissance du parc de logements a permis de soutenir une croissance annuelle des ménages de 0,95 %. Pour atteindre le taux de croissance projeté de 0,68 % par l'ISQ pour les 20 prochaines années, avec le même ratio de construction de logements par rapport à la formation de ménages, il faudrait un taux de croissance annuelle brute du parc de logements de 0,91 %. En prenant comme base les 166 610 logements privés occupés en 2021, cela équivaut à environ 1 650 nouvelles mises en chantier par an pour les 20 prochaines années. Ce chiffre est en fait nettement inférieur au nombre d'unités commencées à tout moment depuis la fin des années 1990.

La conclusion est que les tendances actuelles de développement résidentiel devraient suffire à soutenir la croissance totale attendue des ménages de Laval au cours des deux prochaines décennies. Cependant, plusieurs autres tendances démographiques sont à noter. Nous avons déjà observé un glissement de la propriété vers la location, en cours depuis 2016, et cette tendance est susceptible de se poursuivre en l'absence de changements majeurs dans les projets de développement futurs. Deuxièmement, une augmentation des ménages d'une personne a été observée à Laval au cours des 25 dernières années. Cette tendance reflète probablement le changement de position de Laval dans la grande région de Montréal, passant d’une communauté de banlieue à une ville centrale, et elle devrait se poursuivre en l'absence de nouveaux investissements dans des logements de taille familiale. Enfin, TKTK adultes plus âgés TKTK à ajouter.

# 11.1.5 Besoins spécifiques en logement social et abordable

### ANGLAIS

There are clear disparities between the need for affordable housing and the availability of such housing. Approximately seven percent of tenant households live in subsidized housing. However, a much greater share of tenant households live in substandard housing, when judged by the criteria of affordability, suitability or adequacy. The implication is that there is insufficient supply of housing to adequately meet the needs of Laval residents with low incomes.

At the same time, it appears that the need for social and affordable housing is not becoming greater over time. On the one hand, the share of households in subsidized housing has remained steady over the last ten years. On the other, during the same time frame it is possible that the need for subsidized housing has declined somewhat, since core housing need prevalence has declined. (However, this trend relies on a data point from 2021 which may be unreliable, since temporary Covid low-income supports were in place in May 2021 when the census was enumerated.) This implies that, while the need for affordable housing remains acute, it has not been increasing over time.

### FRANÇAIS

Il existe des disparités évidentes entre le besoin en logements abordables et leur disponibilité. Environ 7 % des ménages locataires vivent dans des logements subventionnés, mais une proportion bien plus importante vit dans des logements inadéquats selon les critères d’abordabilité, de taille convenable ou de qualité. Cela indique une offre insuffisante pour répondre adéquatement aux besoins des résidents à faible revenu de Laval.

En même temps, il semble que le besoin en logements sociaux et abordables ne s'accentue pas avec le temps. D’une part, la proportion de ménages en logements subventionnés est restée stable au cours des dix dernières années. D’autre part, la prévalence des besoins impérieux en logement a légèrement diminué, ce qui pourrait indiquer un recul du besoin en logements subventionnés. Toutefois, cette tendance repose sur des données de 2021 qui pourraient être biaisées par les soutiens temporaires liés à la Covid-19, en vigueur au moment du recensement. Cela suggère que, bien que le besoin en logements abordables demeure critique, il ne semble pas augmenter avec le temps.
