---
title: "Méthodologie"
author: "Curbcut"
output: html_document
---

#### Échelles territoriales
L'analyse s’appuie principalement sur les districts électoraux définis lors des élections municipales de 2021, accessibles sur le site Données Québec (https://www.donneesquebec.ca/recherche/dataset/limites-des-districts-electoraux-des-dernieres-elections-municipales). Lorsque des analyses plus granulaires sont nécessaires, les aires de diffusion du recensement canadien, qui regroupent généralement entre 400 et 700 habitants, sont utilisées.

#### Utilisation des données du recensement canadien
Afin de garantir la confidentialité des informations du recensement canadien, les données sont soumises à un arrondi aléatoire (vers le haut ou vers le bas) en multiples de 5 ou 10. Cela signifie que chaque valeur est légèrement ajustée, ce qui peut entraîner des divergences lorsque les valeurs sont agrégées. Par exemple, les totaux ou sous-totaux peuvent ne pas correspondre exactement à la somme des valeurs individuelles en raison de cet arrondi indépendant. De même, les pourcentages calculés à partir des données arrondies peuvent ne pas totaliser précisément 100 %.

Lorsque les données du recensement canadien sont présentées à l’échelle des districts électoraux, une interpolation spatiale a été appliquée à partir des secteurs de recensement. L'approche consiste à attribuer aux districts une proportion de la valeur d'un secteur en fonction de la superficie du secteur se trouvant dans chaque district. Par exemple, si un secteur comptant 900 locataires est divisé entre deux districts, avec 1/3 de son territoire dans le district A et 2/3 dans le district B, alors 300 locataires seront attribués au district A et 600 au district B.

L’arrondi aléatoire des valeurs en multiples de 5 introduit une marge d’erreur qui peut s’amplifier lors des calculs par interpolation, particulièrement pour les petites valeurs. L’addition de ces erreurs d’arrondi peut ainsi affecter la précision des valeurs finales attribuées aux districts. Pour des données plus précises, il est possible de commander une découpe territoriale personnalisée auprès de Statistique Canada.

#### Code source ouvert et graphiques en haute définition
Les graphiques de haute qualité et le code source de l’analyse sont accessibles via le dépôt public GitHub : https://github.com/Curbcut/laval-housing. Notez que les données potentiellement privées ne sont pas publiquement disponibles dans ce dépôt.

#### Plateforme publique
Une partie des données présentées dans ce rapport est également disponible sur la plateforme Curbcut à l'adresse : curbcut.ca/laval.